version: '3.9'

services:
  front:
    container_name: inventory_tracker_front
    build:
      context: ./front
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - back

  back:
    container_name: inventory_tracker_back
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_NAME: inventory_tracker
      DATABASE_USER: inventory_tracker
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    networks:
      - back-net
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: inventory_tracker_db
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    networks:
      - back-net
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: inventory_tracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_tracker

  adminer:
    container_name: inventory_tracker_adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha-dark
      ADMINER_DEFAULT_SERVER: db
    networks:
      - back-net
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  back-net:
    driver: bridge

volumes:
  db_data:
