version: '3.9'

services:
  front:
    container_name: inventory_tracker_front
    build:
      context: .
      dockerfile: ./front/Dockerfile.dev
    restart: always
    ports:
      - "4200:4200"

  back:
    container_name: inventory_tracker_back
    build:
      context: .
      dockerfile: ./back/Dockerfile.dev
    restart: always
    networks:
      - back-net
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: inventory_tracker_db
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    networks:
      - back-net
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: inventory_tracker
      POSTGRES_DB: inventory_tracker

  adminer:
    image: adminer
    restart: always
    networks:
      - back-net
    ports:
      - 8080:8080

networks:
  back-net:
    driver: bridge
