version: '3.9'

services:
  front:
    container_name: inventory_tracker_front
    build:
      context: ./front
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"

  back:
    container_name: inventory_tracker_back
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - back-net
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: inventory_tracker_db
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    networks:
      - back-net
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: inventory_tracker
      POSTGRES_DB: inventory_tracker

  adminer:
    container_name: inventory_tracker_adminer
    image: adminer
    restart: always
    networks:
      - back-net
    ports:
      - 8080:8080

networks:
  back-net:
    driver: bridge

volumes:
  db_data:
