# Description: Dockerfile for the development environment of the front-end application.

## Stage 1: Build the application
# Using node image as base
FROM node:slim as base

# Setting up the work directory
WORKDIR /usr/src/app

# Copying all the files in our project
COPY . /usr/src/app/

# Installing angular cli
RUN npm install -g @angular/cli --save-dev

# Installing dependencies
RUN npm install --save-dev


## Stage 2: Running the application
# Using the base image
FROM base as dev

# Starting the web server
CMD ["ng", "serve", "--host", "0.0.0.0"]

# Exposing server port
EXPOSE 4200
